### ISSUE TITLE
Integration test issues

### ISSUE THREAD

**Issue by Ferret-san** [qtumproject/janus#28]
Running truffle test for the integration test against Oppenzeppelin contracts yields tests that do not pass. 

**Warnings**
- WARN expectRevert: Assertions may yield false negatives! Revert reason checks are only known to work on Ganache >=2.2.0 and Hardhat, and the current node is QTUM ETHTestRPC/ethereum-js.

**Errors encountered during testing**
Below is a list compiling of the errors that were found during testing.

- qtum [code: -4] Private key not available 
- qtum [code: -8] Incorrect params 
- Error: Returned error: Unsupported method eth_getBlockByHash 
- Returned error: VM exception: Revert 
- Error: The transaction receipt didn't contain a contract address. 
- Error: Returned error: qtum [code: -5] Address does not exist
- Error: Returned error: invalid character 'W' looking for beginning of value
- Error: Returned error: qtum [code: -3] Invalid amount
- Transaction:  exited with an error (status 0).
      -     Please check that the transaction:
      -     satisfies all conditions set by Solidity `require` statements.
      -     has enough gas to execute the full transaction.
      -     does not trigger a Solidity `revert` statement.

**Comment by ripply** [comment]
Closing this, openzeppelin integration tests run in GitHub actions with a custom runner that filters out tests that don't work so we can see when changes fix/break things.
